### ISSUE TITLE
Error in database internal command

### ISSUE THREAD

**Issue by casmssm** [ubis/Freya#9] opened 2023-10-02 10:54 UTC
Hi, first congratulation for this deployment.

I deployed this solution using Docker with 2 containers MySQL + Server.

I've get this error on login in an account with character builded. The character not show and I see a create button, not it name.
Another question, I see the database and not found a bind between character and account, missing something?

==> /home/server/cabal/log/masterserver.log <==
2023-10-02 07:16:50.627 [ERROR] [DATABASE] Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', face, color, hair, aura, gender, show_helmet FROM characters WHERE id = ?' at line 1

Another issue with this deployment type is after login, the Cabal client try to connect in the internal ip address of GameServer and not the address set in the configuration. I changed the container interface to be the same of the host and works.

**Comment by ubis** [comment] 2023-10-02 12:48
Hi,

I assume you're using the latest build? Could you share your `characters` table?

As for 
>  the Cabal client try to connect in the internal ip address of GameServer and not the address set in the configuration.

This is because of d1645828ad59a42219231d6e897e938977c40c8c which allows to connect locally and remotely. I might make this configurable.

**Comment by artem-alekseev** [comment] 2023-12-21 22:07
@ubis the word "rank" it's reserved word in sql, change the column name

**Comment by ubis** [comment] 2023-12-22 08:06
@artem-alekseev can you also reproduce this?

It seems `rank` is reserved keyword since MySQL 8.0.2, probably because of `RANK()` function. I guess adding backticks might help.

Though it's weird, I don't get this on my dev server on macOS with MariaDB 11.2.2 nor on my test server on FreeBSD with MariaDB 10.11.5

**Comment by artem-alekseev** [comment] 2023-12-22 08:10
@ubis yep u right, it's error only in mysql, mariadb don't have this problem

**Comment by ubis** [comment] 2023-12-22 08:20
Aha, that's the first difference I've heard between MariaDB and MySQL. Any reason you guys are using MySQL over MariaDB? IMO MySQL is slowly being killed by Oracle.

Anyway, we should still fix this. @artem-alekseev if you have MySQL installed, could you check with backticks?

**Comment by artem-alekseev** [comment] 2023-12-22 08:23
I'll take a look tonight and check it out and send you a PR.

**Comment by ubis** [comment] 2023-12-22 10:43
> Another issue with this deployment type is after login, the Cabal client try to connect in the internal ip address of GameServer and not the address set in the configuration. I changed the container interface to be the same of the host and works.

Fixed this with 28e99bd582eec05f85ffba24307547ffc78262b0. Now this behaviour is disabled by default, you can still enable it with `use_local_ip=1` in gameserver conf.

**Comment by artem-alekseev** [comment] 2023-12-22 17:10
> @ubis the word "rank" it's reserved word in sql, change the column name

@ubis  Fixed in #10 

I would like to help you, do some simple things, can you tell me where to start?

**Comment by ubis** [comment] 2023-12-22 17:16
@casmssm everything should be fixed in fb5bbcce67a448075f1b139ee5d269d26f910043 or newer revision.

@artem-alekseev we should chat about this in Discord or so, let's not pollute this issue.

**Closed as completed by ubis** 2023-12-22 17:16 UTC
